config/routes.rb
Rails.application.routes.draw do

root 'principal#index' #Pagina principal
get "/articulos" => "articulos#index", as: "articulos_ver"  #Pagina de los articulos
get "/sobre" => "sobre#index", as: "sobre_ver"  #Pagina sobre la institucion
get "/programas" => "programas#index", as: "programas_ver"  #Pagina de los programas que ofrece la institucion
get "/usuarios" => "users#index", as: "usuarios_ver"  #Pagina de los usuarios

devise_scope :user do
	get "/ingresar" => "devise/sessions#new", as: "new_session_user" #Pagina de Login
    #get "/registrar" => "devise/registrations#new", as: "new_user_registration" #Pagina de Registro
    get "registrar", to: "registro#new"
    get "usuarios", to: "users#create"
    get '/editar' => 'devise/registrations#edit', as: "edit_user_registration" #Pagina para editar usuario
    end

devise_for :users, :controllers => { :registrations => 'registro'}
match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :articulos
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
has_one_attached :image
validates :titulo, presence: true
validates :body, presence: true, length: { minimum: 10 }

#mostrar ultimo de primero
default_scope {order(created_at: :desc)}
paginates_per 6
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  validates :name, presence: true, on: :create
scope :all_except, ->(user) { where.not(id: user) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user.admin?
      usuarios_path
    else
      root_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
  @articulos = Articulo.page params[:page]
  end
  
  def show
  @articulo = Articulo.find(params[:id])
  end
  
  def new
  @articulo = Articulo.new
  end

  def create
  @articulo = Articulo.new(article_params)

    if @articulo.save
      redirect_to @articulo
    else
      render :new
    end
  end
  
  def edit
    @articulo = Articulo.find(params[:id])
  end

  def update
    @articulo = Articulo.find(params[:id])

    if @articulo.update(article_params)
      redirect_to @articulo
    else
      render :edit
    end
  end
  
   def destroy
	@articulo = Articulo.find(params[:id])
    @articulo.destroy

    redirect_to articulos_ver_path
  end
  
  
  private 
    def article_params
      params.require(:articulo).permit(:titulo, :body, :image)
    end
 

end

app/controllers/ingresar_controller.rb
class IngresarController < Devise::SessionsController
  def index
  end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController

  def index
  @articulos = Articulo.all
  end
  
  def show
  @articulo = Articulo.find(params[:id])
  end
  
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  def index
  end
end

app/controllers/registro_controller.rb
class RegistroController < Devise::RegistrationsController
skip_before_action :require_no_authentication, only: [:new, :create]
before_action :authenticate_user
before_action :authenticate_admin

def new
	super
end

def create
  super
end

def delete
  super
end

  private
 def sign_up(resource_name, resource)
   true
 end
   
def authenticate_user
return unless !user_signed_in?
redirect_to root_path
end


def authenticate_admin
	return unless !current_user.admin?
    redirect_to root_path
end
  
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	before_action :authenticate_user
  	before_action :authenticate_admin
  	
  def index
  	@users = User.all_except(current_user)
  end
  
  def create
  super
  end
  
   def destroy
    @users = User.find(params[:id])
    @users.destroy
    redirect_to root_url, notice: "User deleted."
  end
  
  
protected

def authenticate_user
return unless !user_signed_in?
redirect_to root_path
end

def authenticate_admin
	return unless !current_user.admin?
    redirect_to root_path
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/ingresar_helper.rb
module IngresarHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articulos/_error.html.erb
<% if @errors.present? %>
  <div class="alert alert-danger errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/articulos/_form.html.erb
<%= render partial: "error" %>
<%= form_with model: @articulo do |form| %>
  <div class="form-group">
    <%= form.label :título %><br>
    <%= form.text_field :titulo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :texto %><br>
    <%= form.text_area :body, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= form.submit "Guardar", class: "btn btn-default" %>
  </div>
<%= link_to "Volver", '/articulos', class: 'btn btn-default btn-lg btn-block' %><br>
<% end %>

app/views/articulos/edit.html.erb
<section id="contenedor">
<%= render 'layouts/header' %>
<section id="texto">
<h1>Editar Artículo</h1>
<%= render "form", articulo: @articulo %>
</section>
<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>	
</section>

app/views/articulos/index.html.erb
<section id="contenedor">
<section id="cartelera">
<section id="texto">
<h1>Publicaciones</h1>
<p><%= paginate @articulos, window: 0 %></p>
<% if user_signed_in? %>
<%= link_to "Nuevo Artículo", '/articulos/new', class: 'btn btn-default btn-lg btn-block' %>
<% end %>
</section><br>

<div class="articulos">
<% @articulos.each do |articulo| %>
	<div class="articulo">
		<div class="thumbnail">
			<div class="caption">
	        <h3><%= link_to truncate(articulo.titulo, length:20), articulo_path(articulo) %></h3>
	        <p><% if articulo.image.attached? %>
    			<%= image_tag articulo.image, style: "width: 200px; display: run-in" %>
			<% end%>
			<p><%= truncate(articulo.body,length: 30) %></p>
			</p>
			<p>
 
</p>
			<% if user_signed_in? %>
  				<%= link_to "Editar", edit_articulo_path(articulo), class: 'btn btn-default'  %>
  				<%= link_to "Borrar", articulo_path(articulo), class: 'btn btn-default', method: :delete, data: { confirm: "seguro?" } %>
  				<% end %>
	        </div>
	    </div>
	</div>
  <% end %>
  
</div>
<section id="texto">
<p><%= paginate @articulos, window: 0 %></p>
</section><br>

</div>

</div>
</section>
		
<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>
</section>
</section>

app/views/articulos/new.html.erb
<section id="contenedor">
  <%= render 'layouts/header' %>
<section id="texto">
<h1>Nuevo Artículo</h1>
<%= render "form", articulo: @articulo %>	
</section>
<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>
</section>

app/views/articulos/show.html.erb
<section id="contenedor">
<%= render 'layouts/header' %><br>
<section id="texto">
<h1><%= @articulo.titulo %></h1>
<% if @articulo.image.attached? %>
    <%= image_tag @articulo.image, style: "width: 200px" %>
<% end%>
<p><%= @articulo.body %></p>
<p>
  Publicado el <%= @articulo.created_at.strftime("%d/%m/%Y, %l:%M%P") %>
</p>
<%= link_to "Volver", '/articulos', class: 'btn btn-default btn-lg btn-block' %><br>
</section>
<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>
</section>

app/views/ingresar/index.html.erb
<h1>LOGIN</h1>
<p>fiuyuuum</p>
<%= link_to "Volver",'/' %>

app/views/layouts/_footer.html.erb
<div id="push"></div>
	<footer class="footer navbar-fixed-bottom">
	<div class="container">
		<nav>
			<ul>
				<p> si! </p>
			</ul>
		</nav>
	</div>
	</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container-fluid">
		<nav>
			<label for="toggle"><%= image_tag("menu.png", width: '70px') %></label>
				<input type="checkbox" id="toggle" />		
				<ul>
					<li><a><%= link_to "Principal",'/' %></a></li>
						<li><a><%= link_to "Publicaciones", articulos_ver_path %></a></li>
						<% if current_user && current_user.admin %>
						<li><a><%= link_to "Administración", usuarios_ver_path %></a></li>
						<% end%>
					<li><a><%= link_to "Programas", programas_ver_path %></a></li>
					<li><a><%= link_to "Sobre nosotros", sobre_ver_path %></a></li>
					<% if user_signed_in? %>
						<li><a><%= link_to "Salir", destroy_user_session_path, method: :delete  %></a></li>
					<% else %>
						<li><a><%= link_to "Ingresar", new_session_user_path %></a></li>
					<% end %>
				</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<meta name="viewport" content="width-device-width, user-scable-no,initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0">
	<head>
    <title>E.A.O Carmen Cabriles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<% unless current_page?(new_session_user_path) %>
		<%= render 'layouts/header' %>
	<%end%>
    <%= yield %>
    
  </body>
</html>

app/views/principal/index.html.erb
		<% date = DateTime.now.in_time_zone 'Caracas'%>

<section id="contenedor">
<!-- fecha y saludo -->
<section id="noticias">											
		<section class="saludo">
		<h1 class="marquee">
				<marquee width="100%">
					<p id="texto">Le Damos La Bienvenida Al Sistema Web De La Escuela de Artes y Oficios Carmen Cabriles</p>
				</marquee>
		</h1>
		</section>
</section>
<!-- Fin de fecha y saludo -->

<br>
			
<section id="cartelera">
			<section id="texto">
			<p>Bienvenidos a la página de la Escuela de artes y oficios Carmen Cabriles que le presta las últimas noticias de la institución.</p>
			</section>
</section>
<section id="texto">
			<h1 >Publicaciones Recientes:</h1>
</section>
						

<br>
<% i = 0 %>
<div class="articulos">

<% @articulos.each do |articulo| %>
<%i += 1%>
	<div class="articulo">
		<div class="thumbnail">
			<div class="caption">
	        <h3><%= link_to truncate(articulo.titulo, length:20), articulo_path(articulo) %></h3>
	        <p><% if articulo.image.attached? %>
    			<%= image_tag articulo.image, style: "width: 200px; display: run-in" %>
			<% end%>
			<p><%= truncate(articulo.body,length: 30) %></p>
			</p>
			<p>
  Publicado el <%= articulo.created_at.strftime("%d/%m/%Y, %l:%M%P") %>
	</p>
	        </div>
	    </div>
	</div>
	<%if i == 4%>
    	<%break%>
  <%end%>
  <% end %>
</div>
<footer>
		<p>Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>	
</section>
	
</section>

app/views/programas/index.html.erb
<section id="contenedor">
<%= render 'layouts/header' %>
<section id="cartelera" >
<section id="texto">
<h1>Programas</h1>
<%= image_tag("artesyoficios.jpg", width: '300px') %>

<p>Los cursos gratuitos que actualmente presentamos son en las especialidades de:</p>
<div class="articulos">
  <div class="articulo">
    <%= image_tag("dibujo.jpg", width: '150px') %>
    <p>Pintura y dibujo</p>
  </div>
  <div class="articulo">
    <%= image_tag("manualidades.jpg", width: '200px') %>
    <p>manualidades</p>
  </div>
  <div class="articulo">
    <%= image_tag("bisuteria.jpg", width: '150px') %>
    <p>Bisutería</p>
  </div>
  <div class="articulo">
    <%= image_tag("confecion.jpg", width: '150px') %>
    <p>Confección</p>
  </div>
  <div class="articulo">
    <%= image_tag("panadera.jpg", width: '150px') %>
    <p>Reposteria y Panaderia</p>
  </div>
  <div class="articulo">
    <%= image_tag("manicura.jpg", width: '150px') %>
    <p>Manicura y Pedicura</p>
  </div>
 </div><br>
</section>

</section>
<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>
</section>

app/views/sobre/index.html.erb
<section id="contenedor">
<%= render 'layouts/header' %>
<section id="cartelera" >
   <section id="texto">
     <h1>¿Quienes somos?</h1>
     <p>Somos una Escuela estadal dedicada a la instrucción de cursos gratuitos por módulos de las artes aplicadas y de los oficios artísticos.</p>
     <div class="container-fluid" id="mision">
<h2>Mision</h2>
<p>Incentivar la integración de los entes correspondientes en la formación moral,
cívica, cultural y académica de los ciudadanos y ciudadanas; a través de estrategias
que permitan un trabajo socio-productivo. Alcanzando logros significativos que responden
a la visión de un proyecto sustentando en los valores morales y étnicos, así como en las
transformación del quehacer educativo-comunitario.</p>
     </div><br>
     <div class="container-fluid" id="mision">
<h2>Vision</h2>
<p>formar ciudadanos criticos, creativos, participativos, corresponsables de su desarrollo
personal y profesional, con bueno habitos, sustentandos en valores morales y eticos,
reflejadosen una conciencia productiva y asetiva que le permita convivir en sana paz,
armonia y equidad de sus semejantes.</p>
     </div><br>
<p>Estamos ubicados en la zona 2 de los Naranjos, detrás del módulo policial, Guarenas, Municipio plaza, Estado Miranda.</p>
     <p>Para mayor  informacion comunicarse con el correo:<br>
       "jaimesmaryuris@gmail.com"<br>
       o al numero<br>
       0416-329-75-85 </p>
</section>
		</section>

<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>
</section>

app/views/users/index.html.erb
<section id="contenedor">
<section id="texto">
<h1>Lista de Usuarios</h1>

<% if current_user && current_user.admin %>
	<%= link_to "Crear Usuario", new_user_registration_path , class: 'btn btn-default' %>
<br>
<table id='usuario-tabla' class="table table-hover">
            <thead  class="thead-light">
             <tr>
                <th>Usuario</th>
                <th colspan="1"></th>
              </tr>
            </thead>            
            <tbody>
            <% @users.each do |user| %>
                            <tr>
                              <td><%= user.name %></td>
			      <td><%= user.email %></td>
	 <td><%= link_to "Borrar", admin_destroy_user_path(user), method: :delete, data: { confirm: "Seguro?" } , class: 'btn btn-default' %></td>
</tr>
<% end %>
     </tbody>
          </table>                
<%end%>
</section>
<footer>
		<p> Escuela de Artes y oficios Carmen cabriles copyright 2020. Todos los derechos reservados.
</p>
</footer>
</section>